---
title: "Presentations"
---

## Conference

1.  “State-Space Dynamic Functional Regression for Multicurve Fixed Income Spread Analysis and Stress Testing”, 2024 Australasian Actuarial Education and Research Symposium (Nov 2024, Melbourne, Australia)
2.  “Multi-Factor Polynomial Diffusion Models and Inter-Temporal Futures Dynamics in Energy Markets”, 17th International Conference of Computational and Financial Econometrics (Dec 2023, Berlin, Germany)
3.  “State-Space Dynamic Functional Regression for Fixed Income Spread Analysis”, 68th Euro Working Group for Commodity and Financial Modelling (Dec 2023, Abu Dhabi, UAE)
4.  “Multi-Factor Polynomial Diffusion Models and Inter-Temporal Futures Dynamics in Energy Markets”, Mathematics of Risk 2022 (Nov 2022, Melbourne, Australia)
5.  “Multi-Factor Polynomial Diffusion Models and Inter-Temporal Futures Dynamics in Energy Markets”, 4th Australasian Commodity Markets Conference (April 2022, Sydney, Australia)
6.  “On EKF and UKF in Polynomial Diffusion Models for Commodity Futures”, 24th International Congress on Insurance: Mathematics and Economics (Jul 2021, Online)
7.  “On Modelling of Crude Oil Futures in a Bivariate State-Space Framework”, Mathematical and Statistical Methods for Actuarial Sciences and Finance (Sep 2020, Online)
8.  “On the Parameter Estimation in the Schwartz-Smith’s Two-Factor Model”, Research School on Statistics and Data Science (Jul 2019, Melbourne, Australia)

## Seminar

1.  “State-Space Functional Regression for Multi-Term-Structure Dynamics”, Central University of Finance and Economics (Oct 2025, Beijing, China)
2.  “State-Space Functional Regression for Multi-Term-Structure Dynamics”, Peking University (Oct 2025, Beijing, China)
3.  “State-Space Functional Regression for Multi-Term-Structure Dynamics”, Nankai University (Oct 2025, Tianjin, China)
