---
title: "Publications"
---

## Preprints 

1.  He, P., Shang, H.L., Zou, N., [On the Distributed Estimation for Scalar-on-Function Regression Models](https://arxiv.org/abs/2601.04138).
2.  He, P., Peters, G. W., Kordzakhia, N., & Shevchenko, P. V., [Multi-Factor Function-on-Function Regression of Bond Yields on WTI Commodity Futures Term Structure Dynamics](https://arxiv.org/abs/2412.05889).
3.  He, P., Peters, G. W., Kordzakhia, N., & Shevchenko, P. V., [State-Space Dynamic Functional Regression for Multicurve Fixed Income Spread Analysis and Stress Testing](https://arxiv.org/abs/2409.00348).

## Journal Papers

1.  He, P., Kordzakhia, N., Peters, G. W., Shevchenko, P. V. (2025). [PDSim: A Shiny app for simulating and estimating polynomial diffusion models in commodity futures](https://openresearchsoftware.metajnl.com/articles/10.5334/jors.537). *Journal of Open Research Software*, 13, 21.

## Conference Proceedings

1.  He, P., Kordzakhia, N., Peters, G. W., Shevchenko, P. V. (2024). [Multi-factor polynomial diffusion models and inter-temporal futures dynamics](https://link.springer.com/chapter/10.1007/978-3-031-47417-0_18). In *2021-2022 MATRIX Annals* (pp. 363-382). Springer.
2.  He, P., Binkowski, K., Kordzakhia, N., Shevchenko, P. (2021). [On modelling of crude oil futures in a bivariate state-space framework](https://link.springer.com/chapter/10.1007/978-3-030-78965-7_40). In *Mathematical and Statistical Methods for Actuarial Sciences and Finance: eMAF2020* (pp. 273-278). Springer.
3.  Binkowski, K., He, P., Kordzakhia, N., Shevchenko, P. (2019). [On the parameter estimation in the Schwartz–Smith’s two-factor model](https://link.springer.com/chapter/10.1007/978-981-15-1960-4_16). In *Research School on Statistics and Data Science* (pp. 226-237). Springer.
